[package]
name = "hell"
version = "0.1.0"
authors = ["atil <atil@torrenglabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.32"
cgmath = "0.17.0"
gl = "0.14.0"
tobj = "0.1.11"